- CMakeLists.txt
- thtk/util.h
When `_GNU_SOURCE` is not defined, some functions used in util/util.c aren't defined. Without `-std=c99` gcc complains about using for loop initial declarations.
> Fix gcc/glibc build errors

- thecl/CMakeLists.txt
- thecl/eclmap.c
- thecl/eclmap.h
- thecl/ecsparse.y
- thecl/thecl.c
- thecl/thecl.h
- thecl/thecl06.c
- thecl/thecl10.c
This PR adds support for "eclmaps", simple format that I came up with. Here's an example of usage:
```$ thecl -d6m my_th6.map  ecldata1.ecl ecldata1.ecs ```
will decode ecldata1 and translate the instructions to mnemonics using mappings my_th6.map.
First line is "eclmap" (signature), all the other lines are entries:
```<opcode> <signature> <mnemonic>```
1) Opcode is obviously the opcode.
2) Signature is supposed to be the format of the arguments. Right now it's unimplemented.
3) Mnemonic is the mnemonic that the opcode will be translated to/from.
Example:
```0 ? noop```
The question mark means empty field. (Later you will be able to load multiple mappings and combine them into one.)
Here are some example eclmaps:
[map for th06](https://pastebin.com/raw/y0JA8yYp) …
> Added support for mnemonic mappings

- thtk/dat.h
Find this issue when using `thtk` inside a c++ project. This PR simply add the missing code in `dat.h` .
Refer to [thtk/thtk/dat.h(L145)](https://github.com/thpatch/thtk/blob/e5a5e29aff46473b76f425d0b59af2a4e1fec6e1/thtk/dat.h#L145) , it seems we only have a single unpaired `}` if we are using c++.
What added:
``` cpp
#ifdef __cplusplus
extern "C" {
#endif
```
Thanks
BLumia
> Add missing `#ifdef __cplusplus` in dat.h

- util/util.c
When we pass `some_directory` to the `dir` argument, we'll get filepaths like `some_directoryfoo.anm` with current version of `util_scan_files`. This PR fixes the problem.
> util: Fix util_scan_files not adding path delimiter.

- thanm/thanm.1
- thanm/thanm.c
- thdat/thdat.1
- thdat/thdat.c
- thecl/thecl.1
- thecl/thecl.c
- thmsg/thmsg.1
- thmsg/thmsg.c
- util/CMakeLists.txt
- util/mygetopt.c
- util/mygetopt.h
- util/program.c
- util/program.h
Pros:
* More flexible and extensible
* Standard syntax
* Adding an option with argument is no longer PITA
* Multiple ecl maps can be loaded now, just from the fact that you can specify multiple -m switches
Cons:
* Different, incompatible syntax from before (will break any unofficial GUIs)
* ~~Need to rewrite documentation~~ done
* ~~Need to rewrite print_usages~~ done
* Not specifying version for thdat won't work anymore. (setting the default to latest game was dumb anyway :p)
* C standard isn't clear on whether argv[n] is modifiable.
* I haven't tested it that much. Someone plz test.
~~if someone wants to work on documentation, feel free to assign yourself. Otherwise I'll do it myself in 3️⃣ days™️~~  done
(by the way, -d option in thdat is supposed to be used for testing detect. leave …
> Better argument parsing

- thdat/thdat.c
- thecl/thecl.c
- thmsg/thmsg.c
- thstd/thstd.c
- thtk/thdat.c
And now I feel a bit useless but I guess ZUN just didn't see the need for new opcodes. Or he did, we just didn't get them in the demo
> ZUN changed absolutely nothing, let\'s wait for the full release

- thecl/ecsparse.y
- thecl/ecsscan.l
- thecl/expr.c
- thecl/thecl.c
- thecl/thecl.h
- thecl/thecl06.c
- util/list.c
- util/list.h
**New features** (th10+ only):
- difficulty switch expressions: `wait(60:50:40:30);` -> 
```cpp
!E
60;
!N
50;
!H
40;
!LO /* in th10-th128 it's just !L */
30;
!*
wait([-1]);
```
last parameter always gets all remaining diffs, so do `10:20` to get just
```cpp
!E
10;
!NHLO
20;
!*
```
or `1:2:3:4:5` to split lunatic and overdrive (for games that have it)
this only supports basic integer/float literals, putting variables/expressions inside will not work (I might add that later)
- no forced typecast for passing expressions to ins calls: basically now you don't have to do `wait(_S(2+2))`, `wait(2+2)` works just fine
- easy to write float literals that represent radians: `rad(180.0f)` -> `3.14159...f` (since this is just a way of representing a float value and not an actual function, you can't …
> Some new features and bug fixes in thecl

- thecl/ecsparse.y
- thecl/ecsscan.l
thecl does not make the distinction between doubles and singles (one can be added later, like with D or something), and ZUN's ECL engine (almost?) exclusively uses singles. Therefore, values like "1.23" should be recognized as floats, NOT doubles (which, once again, thecl doesn't even know about). Also adds support for values like "+12" and allows integers in the rad() function.
> thecl: better float and rad value handling

- contrib/eclmapcvt.awk
- thecl/CMakeLists.txt
- thecl/eclmap.c
- thecl/ecsparse.y
- thecl/seqmap.c
- thecl/seqmap.h
- thecl/thecl.1
- thecl/thecl.c
- thecl/thecl.h
- thecl/thecl06.c
- thecl/thecl10.c
Convert with `awk -f contrib/eclmapcvt.awk old.map > new.map`
Documentation from manpage
```
ECLMAP FILE FORMAT
Eclmap files, which are added with the -m option,
consist of two kinds of lines: control lines (which
start with ‘!’), and mapping lines.
The file starts with ‘!eclmap’ control line. The rest
of the control lines select the mapping that is being
modified:
‘!ins_names’
Instruction names. This is the default map‐
ping.
Value: identifier
‘!ins_signatures’
Instruction signatures.
Value: signature
‘!gvar_names’
Global variable names.
Value: identifier
‘!gvar_types’
Global variable types.
Value: type (‘$’ for integer, ‘%’ for float)
‘!timeline_ins_names’
Timeline instruction names.
Value: identifier
‘!timeline_ins_signatures’
Timeline instruction signatures.
Value: signature
Mapping …
```
> new eclmap format

- thecl/eclmap.c
- thecl/eclmap.h
- thecl/ecsparse.y
- thecl/ecsscan.l
- thecl/expr.c
- thecl/path.c
- thecl/thecl.c
- thecl/thecl06.c
- thecl/thecl10.c
this fixes the two final r/r conflicts mentioned in #64 
I don't know if sub call as instruction and sub call as expression are really equivalent, so someone please test it. 
I also fixed all of the warnings gcc gave me, so now you can finally build thtk without it giving you three screenfuls of "const qualifier discarded"
> thecl: fix remaining r/r conflicts and warnings

- thtk/thdat.c
This patch removes the unused include, to make other application ([thplayer](https://github.com/BearKidsTeam/thplayer) here) that uses thtk as 3rdparty library life easier :)
> thdat: remove unused include

- thecl/thecl10.c
Operation 1003 changed arguments from "S" to "", so re-compilation was failing
> Fix some operations for thecl

- thecl/thecl.c
- thecl/thecl.h
- thecl/thecl06.c
- thecl/thecl10.c
This might come useful for developing thprac
> Thecl ECL address output with '-x' param

- CMakeLists.txt
- thtk/CMakeLists.txt
We are using thtk as a submodule in our project and prefer to use thtk as static library, but found it currently hard-coded to add as a shared library, and the shared library will also be installed to a incorrect location.
This patch adds an option to let developer choose the library type they want via the standard CMake option `BUILD_SHARED_LIBS`, and also make use of the `ARCHIVE`(for static lib) and `RUNTIME`(for shared lib) type in `install()` to ensure the shared lib and static lib can install to correct location.
> fix: option to prefer static lib, fix lib install path

- thecl/ecsparse.y
- thecl/ecsscan.l
- thecl/thecl.c
- thecl/thecl.h
- thecl/thecl06.c
- thecl/thecl10.c
Not merging yet so people get time to test it a bit more (though it seems like it works and didn't break anything in past games)
> thecl: better support for th185 diffs

- thanm/thanm.c
- thanm/thanm.h
- util/file.c
> th19: support new compressed ANM format

- thtk/thtk.pc.in
According to https://people.freedesktop.org/~dbn/pkg-config-guide.html, the file `thtk/thtk.pc.in` has the wrong syntax.
> thtk: fix pkg-config file

- thtk/thdat02.c
thtk_io_map() creates a read-only memory mapping, but both th02_read() and th02_write() perform writes to the data buffer. This immediately segfaults (well actually it doesn't, because mmap always fails, but that's another story).
This commit fixes it so thtk_io_pread() is used directly instead.
> thdat: fix wrong thtk_io_map() usage in th02_read() and th02_write()

- thecl/thecl10.c
`stackSqrt()` shouldn't take any non-stack arguments.
> Fix ECL sqrt in TH13+

- .github/workflows/build.yml
The current workflow is broken due to spooky dependency mismatching:
```
Error: Missing download info for actions/upload-artifact@v3
```
This error prevents binary artifacts from being generated for Windows targets.
Bumping the version numbers seemed to fix the issue. I tested the x64 artifact and it worked as expected.
* upgraded all actions to v4.
> fix github actions to generate nightly builds

- .github/workflows/build.yml
Adds a Github action to upload builds to https://thcrap.thpatch.net/thtk-nightly/thtk-win32-x86.zip and to https://thcrap.thpatch.net/thtk-nightly/thtk-win32-x64.zip
Only pushs to the master branch are uploaded there (the branch name is tested in a small script on the server, I tested using the "deploy-to-thpatch" branch name in that script and then changed it to "master" while writing this pull request).
The main benefit of this is having a permanent storage for nightly builds. Github Action artifacts last for only 60 days, and they definitely did expire a few times in the past.
Also, please merge using "squash and merge". I have that working on CI stuff requires doing a new commit for every single little change.
> Deploy to thpatch
